### ISSUE TITLE
主办方ip断开

### ISSUE THREAD

**Issue by pkq2019** [geekinglcq/aca#2]
谢谢您的分享，复现了您的代码，出现以下提示：
Data split done
Start
0
HTTPConnectionPool(host='166.111.7.106', port=8081): Max retries exceeded with url: /53f45463dabfaee1c0b25a3d.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f98291d1e10>, 'Connection to 166.111.7.106 timed out. (connect timeout=20)'))

这个是因为主办方服务器关闭了吧？
这，，是不是无解了？    您知道其他接入方式么

**Comment by geekinglcq** [comment]
服务器关了就没有办法从原来比赛中给的这个IP来获取结果了。 
但是实际上这些数据都是谷歌的搜索数据，所以对于每个学者，用“学者名   机构名”去query谷歌，得到的第一页就是所需数据，只不过比赛的时候主办方为了稳定（因为搜索结果可能会变）提前把这些搜索结果存到自己的服务器上去了。
