### ISSUE TITLE
开放学术精准画像大赛任务三的数据

### ISSUE THREAD

**Issue by gaolblog** [geekinglcq/aca#3]
作者您好，task3的数据下载链接已经取消了，可以发送我一份zip数据吗？万分感谢您了syhkht11016@163.com

**Comment by Legend94rz** [comment]
https://biendata.com/competition/scholar/data/
点击标题栏上“EN/中”字样，把语言切换为英文，可以下载到dropbox里的数据，可能需要梯子。

**Comment by gaolblog** [comment]
您好作者，您手头有task3的zip数据集吗？VPN这个搞不定啊，能不能给我百度网盘分享一份啊啊





在 2019-05-23 11:31:06，"Legend" <notifications@github.com> 写道：


https://biendata.com/competition/scholar/data/
点击标题栏上“EN/中”字样，把语言切换为英文，可以下载到dropbox里的数据，可能需要梯子。

**Comment by Legend94rz** [comment]
链接: https://pan.baidu.com/s/1fyUasS4fcZOjEDs77pR9kA 提取码: 35qe

**Comment by gaolblog** [comment]
收到，谢谢！以后有不懂的问题希望能请教您，和您交流，麻烦了。

在 2019-05-23 16:39:48，"Legend" <notifications@github.com> 写道：


链接: https://pan.baidu.com/s/1fyUasS4fcZOjEDs77pR9kA 提取码: 35qe
